// WORDS_PART1 — Massive expansion for Kurdisch Badini (Kurmanci) learning app
// Categories: food, verbs, adjectives, phrases
// Checked against words-data.ts (2302 entries) — NO duplicates

export const WORDS_PART1 = [

  // =============================================
  // FOOD — New entries not in existing 165 food items
  // =============================================

  // Kurdish/regional dishes & preparations
  { de: "Tepsi (Auflauf)", ku: "Tepsî", c: "food", n: "Kartoffel-Auberginen-Auflauf" },
  { de: "Kubba", ku: "Kubba / Kibbe", c: "food", n: "gefüllte Bulgurbällchen" },
  { de: "Tikka", ku: "Tikka", c: "food", n: "mariniertes Grillfleisch" },
  { de: "Fleischspiess", ku: "Şîş kebab", c: "food" },
  { de: "Leber (Essen)", ku: "Ceger", c: "food" },
  { de: "Innereien", ku: "Sirawî / Cigerê pez", c: "food" },
  { de: "Fischgericht", ku: "Masiyê biryankî", c: "food" },
  { de: "gebratener Reis", ku: "birincê qelandî", c: "food" },
  { de: "Reisauflauf", ku: "birincê bi firnê", c: "food" },
  { de: "Pilaw", ku: "Pilaw", c: "food" },
  { de: "Sarma", ku: "Sarma / Yaprax", c: "food", n: "gefüllte Kohlblätter" },
  { de: "gefüllte Paprika", ku: "bîberên tijîkirî", c: "food" },
  { de: "Lahmacun", ku: "Lahmacûn", c: "food", n: "dünne Fleischpizza" },
  { de: "Samosa", ku: "Samûsa / Börek", c: "food" },
  { de: "Börek", ku: "Börek / Gullîçe", c: "food" },
  { de: "Aufstrich", ku: "Rûnê nan", c: "food" },
  { de: "Pickles", ku: "Tirşî / Turşî", c: "food" },
  { de: "eingelegtes Gemüse", ku: "sebzeyên tirşkirî", c: "food" },
  { de: "Pacha", ku: "Paça / Kelle paça", c: "food", n: "Suppengericht mit Schaf" },
  { de: "Tirit", ku: "Tirît", c: "food", n: "Brot mit Brühe" },

  // More tea culture & beverages
  { de: "Teelöffel", ku: "kevçîya çayê", c: "food" },
  { de: "Teekocher (Samowar)", ku: "Semawerê çayê", c: "food" },
  { de: "Zuckerwürfel", ku: "qûtiya şekir / şekirê qube", c: "food" },
  { de: "Kardamom-Tee", ku: "çayê bi hel", c: "food" },
  { de: "Kardamom", ku: "Hel", c: "food" },
  { de: "Safran", ku: "Zeferan", c: "food" },
  { de: "heisses Wasser", ku: "ava germ", c: "food" },
  { de: "kaltes Wasser", ku: "ava sar", c: "food" },
  { de: "kochendes Wasser", ku: "ava kelandî", c: "food" },
  { de: "Trinkwasser", ku: "ava vexwarinê", c: "food" },
  { de: "Traubenmelasse", ku: "Dims / Doşav", c: "food" },
  { de: "Traubensaft", ku: "ava tirî / şîrê tirî", c: "food" },
  { de: "Orangensaft", ku: "ava pirteqalê", c: "food" },
  { de: "Apfelsaft", ku: "ava sêvan", c: "food" },
  { de: "Milchshake", ku: "şîrê tevlihev", c: "food" },

  // Baking & bread culture
  { de: "Sauerteig", ku: "hevîrê tirş / hevîrtirşk", c: "food" },
  { de: "Hefeteig", ku: "hevîrê bi mayê", c: "food" },
  { de: "Hefe", ku: "Maye", c: "food" },
  { de: "dünn ausrollen", ku: "hevîr raxistin", c: "food" },
  { de: "Ofen vorheizen", ku: "firnê germ kirin", c: "food" },
  { de: "Backblech", ku: "tepsiya firnê", c: "food" },
  { de: "Brotkorb", ku: "selika nanî", c: "food" },
  { de: "Tischdecke", ku: "sofre / bermalî", c: "food" },
  { de: "Serviette", ku: "Peçete / Desmal", c: "food" },

  // Additional cooking terms
  { de: "salzen", ku: "xwê lê kirin / xwê dan", c: "food" },
  { de: "pfeffern", ku: "bîber lê kirin", c: "food" },
  { de: "umrühren", ku: "hejiqandin / bi tevger kirin", c: "food" },
  { de: "einweichen", ku: "di avê de hiştin", c: "food" },
  { de: "abtropfen lassen", ku: "av jê kirin / ava wê avêtin", c: "food" },
  { de: "anrichten", ku: "xwarinê raxistin", c: "food" },
  { de: "probieren", ku: "tamkirin / çêştkirin", c: "food" },
  { de: "schneiden (dünn)", ku: "bi hûrî birîn", c: "food" },
  { de: "würfeln (Gemüse)", ku: "bi çargoşe birîn", c: "food" },
  { de: "stampfen", ku: "pêkutan / hêlîkirin", c: "food" },
  { de: "auf kleiner Flamme kochen", ku: "bi agirê kêm kelandin", c: "food" },
  { de: "goldbraun braten", ku: "qelandin heta bibe zêrîn", c: "food" },

  // Food adjectives & restaurant terms
  { de: "hausgemacht", ku: "çêkirina malê / yê malê", c: "food" },
  { de: "traditionell (Essen)", ku: "xwarina kevneşopî / yê berê", c: "food" },
  { de: "Bestellung", ku: "Siparîş", c: "food" },
  { de: "Koch (Person)", ku: "Aşpêj / Pêjker", c: "food" },
  { de: "Speisekarte", ku: "Menuya xwarinê / Lîste", c: "food" },
  { de: "Tischreservierung", ku: "Rezervasyona maseyê", c: "food" },
  { de: "Selbstbedienung", ku: "Xizmetkirina xwe bi xwe", c: "food" },
  { de: "zum Mitnehmen", ku: "ji bo bi xwe re birin", c: "food" },
  { de: "Imbiss", ku: "Xwarina bilez / Fast food", c: "food" },
  { de: "Strassenessen", ku: "Xwarina kolanan", c: "food" },

  // Nuts, grains, extras
  { de: "Sonnenblumenkerne", ku: "tovê gulberojê / bizir", c: "food" },
  { de: "Kürbiskerne", ku: "tovê kundirê", c: "food" },
  { de: "Erdnüsse", ku: "fistiqê erdê", c: "food" },
  { de: "Trockenfrüchte", ku: "fêkiyên zuwa / mêweyên hişkkirî", c: "food" },
  { de: "Cornflakes", ku: "Korniflêks / Gevrekên lazûtê", c: "food" },
  { de: "Popcorn", ku: "Popkorn / Çitleme", c: "food" },
  { de: "Reiswasser", ku: "ava birincî", c: "food" },
  { de: "Hühnerbrühe", ku: "şorbeya mirîşkê / ava mirîşkê", c: "food" },
  { de: "Tomatensosse", ku: "sosê bacanan", c: "food" },
  { de: "scharfe Sosse", ku: "sosê tûj / acûka tûj", c: "food" },
  { de: "Senf", ku: "Xerdel", c: "food" },
  { de: "Ketchup", ku: "Ketçap", c: "food" },
  { de: "Mayonnaise", ku: "Mayonêz", c: "food" },

  // =============================================
  // VERBS — New entries not in existing 272 verbs
  // =============================================

  // More daily routines
  { de: "sich waschen", ku: "xwe şuştin", c: "verbs" },
  { de: "sich die Haare waschen", ku: "porê xwe şuştin", c: "verbs" },
  { de: "Zähne putzen", ku: "diranan şuştin / fircekirin", c: "verbs" },
  { de: "sich abtrocknen", ku: "xwe zuwa kirin", c: "verbs" },
  { de: "sich schminken", ku: "xwe xemilandin / makyaj kirin", c: "verbs" },
  { de: "sich ausruhen", ku: "xwe rehet kirin / bîhn vedan", c: "verbs" },
  { de: "gähnen", ku: "bavêşîn / bawêşîn", c: "verbs" },
  { de: "schnarchen", ku: "xirîn / bi xirxir razîn", c: "verbs" },
  { de: "aufbleiben", ku: "hişyar man / nerazîn", c: "verbs" },
  { de: "spazieren gehen", ku: "gerîn / mêşîn", c: "verbs" },

  // Domestic & practical verbs
  { de: "saugen (Staubsauger)", ku: "bi kersûgê paqij kirin", c: "verbs" },
  { de: "abwaschen (Geschirr)", ku: "firaqan şuştin", c: "verbs" },
  { de: "aufhängen (Wäsche)", ku: "cilan helandin / daliqandin", c: "verbs" },
  { de: "giessen (Pflanzen)", ku: "gula av dan / av kirin", c: "verbs" },
  { de: "einpacken", ku: "pêçan / pakêt kirin", c: "verbs" },
  { de: "auspacken", ku: "vekirin / pakêt vekirin", c: "verbs" },
  { de: "sortieren", ku: "rêz kirin / dabeş kirin", c: "verbs" },
  { de: "lagern", ku: "hilanîn / veşartin", c: "verbs" },
  { de: "entsorgen", ku: "avêtin / ji holê rakirin", c: "verbs" },
  { de: "schleifen (schärfen)", ku: "tûj kirin", c: "verbs" },

  // Social & interpersonal
  { de: "willkommen heissen", ku: "pêşwazî kirin / bi xêr hatin gotin", c: "verbs" },
  { de: "vorstellen (jemanden)", ku: "nasandin / dan nasîn", c: "verbs" },
  { de: "kennenlernen", ku: "nas kirin", c: "verbs" },
  { de: "sich unterhalten", ku: "sohbet kirin / peyivîn", c: "verbs" },
  { de: "klatschen (reden)", ku: "gotegot kirin / xirgotîn", c: "verbs" },
  { de: "beraten", ku: "şîret kirin / mişewere kirin", c: "verbs" },
  { de: "sich versprechen", ku: "soz dan / qise dan", c: "verbs" },
  { de: "beleidigen", ku: "heqaret kirin / dijûn dan", c: "verbs" },
  { de: "loben", ku: "pesndan / pîroz kirin", c: "verbs" },
  { de: "kritisieren", ku: "rexne kirin", c: "verbs" },
  { de: "flirten", ku: "bi çav girêdan / lîstik kirin", c: "verbs" },
  { de: "sich anfreunden", ku: "hevaltî kirin / dost bûn", c: "verbs" },

  // Trade & business
  { de: "handeln (verhandeln)", ku: "danûstandin kirin / bazirganî kirin", c: "verbs" },
  { de: "tauschen (Geld)", ku: "guheztin / pere guheztin", c: "verbs" },
  { de: "leihen (jemandem)", ku: "deyn dan / eriyet kirin", c: "verbs" },
  { de: "schulden", ku: "deyndar bûn", c: "verbs" },
  { de: "berechnen (Preis)", ku: "hesab kirin / bihay ... danîn", c: "verbs" },
  { de: "erben", ku: "mîras wergirtin", c: "verbs" },
  { de: "vererben", ku: "mîras hiştin", c: "verbs" },
  { de: "versichern", ku: "sîgorte kirin", c: "verbs" },

  // Learning & knowledge
  { de: "auswendig lernen", ku: "ji ber kirin", c: "verbs" },
  { de: "wiederholen", ku: "dubare kirin", c: "verbs" },
  { de: "üben", ku: "pratîk kirin / temrîn kirin", c: "verbs" },
  { de: "buchstabieren", ku: "tîp bi tîp gotin", c: "verbs" },
  { de: "aussprechen", ku: "bilêv kirin / telafuz kirin", c: "verbs" },
  { de: "markieren", ku: "nîşan kirin / xal kirin", c: "verbs" },
  { de: "korrigieren", ku: "serast kirin / rast kirin", c: "verbs" },
  { de: "bestehen (Prüfung)", ku: "serkeftin / derbas bûn", c: "verbs" },
  { de: "durchfallen (Prüfung)", ku: "têk çûn / nebaş derketin", c: "verbs" },
  { de: "abschliessen (Studium)", ku: "xilas kirin / qedandin", c: "verbs" },

  // Technology-related
  { de: "tippen (Tastatur)", ku: "nivîsandin / tipkirin", c: "verbs" },
  { de: "einloggen", ku: "têketin / login kirin", c: "verbs" },
  { de: "scrollen", ku: "gorr kirin / jor û xwar kirin", c: "verbs" },
  { de: "weiterleiten", ku: "şandin / ji ... re şandin", c: "verbs" },
  { de: "markieren (taggen)", ku: "nîşan kirin / tag kirin", c: "verbs" },
  { de: "suchen (online)", ku: "lêgerîn / gerrandin", c: "verbs" },
  { de: "sichern (Daten)", ku: "pişt girtin / backup kirin", c: "verbs" },
  { de: "neu starten", ku: "ji nû ve destpêkirin", c: "verbs" },
  { de: "laden (Akku)", ku: "şarj kirin / dagirtin", c: "verbs" },
  { de: "verbinden (Internet)", ku: "girêdan / pêve kirin", c: "verbs" },

  // Emotion/state verbs (not yet in existing)
  { de: "staunen", ku: "şaş man / mat man", c: "verbs" },
  { de: "sich ekeln", ku: "qirêj hatin / nefret kirin ji", c: "verbs" },
  { de: "sich schämen (beschämt sein)", ku: "şerm bûn / rûreş bûn", c: "verbs" },
  { de: "verzeihen", ku: "efû kirin / bexşandin", c: "verbs" },
  { de: "sich gewöhnen", ku: "fêr bûn / xwe tev kirin", c: "verbs" },
  { de: "sich entspannen", ku: "xwe rehet kirin / rihet bûn", c: "verbs" },
  { de: "einschüchtern", ku: "tirsandin / traş kirin", c: "verbs" },
  { de: "aufgeben", ku: "dev jê berdan / dest jê berdan", c: "verbs" },
  { de: "durchhalten", ku: "berdewam kirin / sebir kirin", c: "verbs" },
  { de: "akzeptieren", ku: "qebûl kirin / pejirandin", c: "verbs" },

  // Physical/body verbs (not yet in existing)
  { de: "kauen", ku: "cûtin / cawiştin", c: "verbs" },
  { de: "schlucken", ku: "daqurtandin", c: "verbs" },
  { de: "spucken", ku: "tif kirin", c: "verbs" },
  { de: "lecken", ku: "lîstin / bi ziman dan", c: "verbs" },
  { de: "beissen", ku: "gwehtin / gez kirin", c: "verbs" },
  { de: "kratzen", ku: "xirişandin / xuriştin", c: "verbs" },
  { de: "streicheln", ku: "dest lê kişandin / nav kirin", c: "verbs" },
  { de: "klopfen", ku: "lê dan / lêxistin", c: "verbs" },
  { de: "klatschen (Hände)", ku: "çepik lê xistin", c: "verbs" },
  { de: "nicken", ku: "serê xwe hejand (erê)", c: "verbs" },
  { de: "Kopf schütteln", ku: "serê xwe hejand (na)", c: "verbs" },
  { de: "blinzeln", ku: "çav dan hev", c: "verbs" },
  { de: "starren", ku: "çav lê man / çav mêze kirin", c: "verbs" },
  { de: "riechen", ku: "bîhn kirin", c: "verbs" },
  { de: "schmecken", ku: "tam kirin / çêşt kirin", c: "verbs" },
  { de: "anfassen", ku: "dest lê dan / dest danîn ser", c: "verbs" },

  // Nature/weather verbs
  { de: "tröpfeln", ku: "dilopîn / bi dilop barîn", c: "verbs" },
  { de: "hageln", ku: "teyrok barîn / zirbe barîn", c: "verbs" },
  { de: "donnern", ku: "bir û brûsk bûn / ewran qîrîn", c: "verbs" },
  { de: "blitzen", ku: "birûsk ketîn", c: "verbs" },
  { de: "scheinen (Sonne)", ku: "roj derketin / tav hatin", c: "verbs" },
  { de: "austrocknen", ku: "zuwa bûn / hişk bûn", c: "verbs" },
  { de: "frieren (Wasser)", ku: "cemidîn / qeşa girtin", c: "verbs" },
  { de: "wehen (Wind)", ku: "ba hatin / ba dan", c: "verbs" },

  // =============================================
  // ADJECTIVES — New entries not in existing 167 adjectives
  // =============================================

  // More physical descriptions
  { de: "schlank", ku: "ziravûdirêj / bejnzirav", c: "adjectives" },
  { de: "muskulös", ku: "bi masûlke / xurt", c: "adjectives" },
  { de: "sommersprossig", ku: "bi kelok / bi xalên rûyê", c: "adjectives" },
  { de: "blass", ku: "zer / zerikî", c: "adjectives" },
  { de: "gebräunt", ku: "bi tav şewitî / esmer", c: "adjectives" },
  { de: "faltig", ku: "bi çirûsk / çilmisî", c: "adjectives" },
  { de: "attraktiv", ku: "balkêş / xweşik", c: "adjectives" },
  { de: "hager", ku: "lawir / zirav", c: "adjectives" },
  { de: "untersetzt", ku: "kurt û qelew / piçûk û stûr", c: "adjectives" },
  { de: "mittelgross", ku: "bi bejnê navîn / ne kurt ne dirêj", c: "adjectives" },
  { de: "barfuss", ku: "xwarpê / lingê xwezayî", c: "adjectives" },

  // Character traits (new, not duplicating existing)
  { de: "nachdenklich", ku: "bi fikirîn / ramîsandî", c: "adjectives" },
  { de: "spontan", ku: "bê plan / yekser", c: "adjectives" },
  { de: "abenteuerlustig", ku: "serpêhatîxwaz / maceracî", c: "adjectives" },
  { de: "aufrichtig", ku: "dilpak / rast", c: "adjectives" },
  { de: "humorvoll", ku: "bi henekî / bi şuxûlî", c: "adjectives" },
  { de: "ernsthaft", ku: "cidî / bi giranî", c: "adjectives" },
  { de: "hartnäckig", ku: "serhişk / bi înad", c: "adjectives" },
  { de: "anpassungsfähig", ku: "bi şiyanbûn / têkildar", c: "adjectives" },
  { de: "diszipliniert", ku: "bi dîsîplîn / rêkûpêk", c: "adjectives" },
  { de: "chaotisch", ku: "tevlihev / bê rêk", c: "adjectives" },
  { de: "selbstbewusst", ku: "bi xweber / xwebawer", c: "adjectives" },
  { de: "sympathisch", ku: "sempatîk / dilxweş", c: "adjectives" },
  { de: "unsympathisch", ku: "nexweşik / bêxweşî", c: "adjectives" },
  { de: "hilfsbereit", ku: "alîkar / dilnerm", c: "adjectives" },
  { de: "egoistisch", ku: "xweparêz / bênav û nîşan", c: "adjectives" },
  { de: "realistisch", ku: "rastbîn / bi rastî", c: "adjectives" },
  { de: "romantisch", ku: "romantîk / evîndar", c: "adjectives" },
  { de: "sorgfältig", ku: "bi baldarî / bi hişyarî", c: "adjectives" },
  { de: "nachlässig", ku: "qerf / bê bal", c: "adjectives" },
  { de: "verantwortungsvoll", ku: "berpirsyar / bi berpirsiyarî", c: "adjectives" },
  { de: "unzuverlässig", ku: "bêemnet / nebawer", c: "adjectives" },

  // Taste, texture, food-related (new, not overlapping)
  { de: "pfeffrig", ku: "bi bîber / bi bîhna bîberê", c: "adjectives" },
  { de: "aromatisch", ku: "bi bîhn / bîhnxweş", c: "adjectives" },
  { de: "cremig", ku: "bi qaymaq / nerm û rûn", c: "adjectives" },
  { de: "saftig", ku: "bi av / avdêr", c: "adjectives" },
  { de: "zäh (Fleisch)", ku: "req / hişk", c: "adjectives" },
  { de: "zart (Fleisch)", ku: "nerm / sivik", c: "adjectives" },
  { de: "lauwarm", ku: "nîvgerm / şil germ", c: "adjectives" },
  { de: "geräuchert", ku: "dûxwarî / bi dûxan", c: "adjectives" },
  { de: "gebraten", ku: "qelandî / birijandin", c: "adjectives" },
  { de: "gegrillt", ku: "biraştî / li ser agir çêkirî", c: "adjectives" },
  { de: "gedünstet", ku: "bi buharê çêkirî", c: "adjectives" },
  { de: "mariniert", ku: "marine kirî / di sos de mayî", c: "adjectives" },

  // Size, quantity, degree (new)
  { de: "zahlreich", ku: "bi hejmar / gelek", c: "adjectives" },
  { de: "einzigartig", ku: "yekta / bêhempa", c: "adjectives" },
  { de: "häufig", ku: "pir caran / zûzû", c: "adjectives" },
  { de: "ausreichend", ku: "têr / bes", c: "adjectives" },
  { de: "unzureichend", ku: "ne têr / kêm", c: "adjectives" },
  { de: "komplett", ku: "temam / bi tevahî", c: "adjectives" },
  { de: "unvollständig", ku: "ne temam / kêm", c: "adjectives" },
  { de: "extra", ku: "zêde / ji wê zêdetir", c: "adjectives" },
  { de: "übermässig", ku: "zêde ji radeyê / pir zêde", c: "adjectives" },
  { de: "gleichmässig", ku: "bi rêk / wekhev", c: "adjectives" },

  // Quality & condition (new)
  { de: "perfekt", ku: "bê kêmasî / kamil", c: "adjectives" },
  { de: "mangelhaft", ku: "bi kêmasî / ne baş", c: "adjectives" },
  { de: "wertvoll", ku: "bi nirx / giranbiha", c: "adjectives" },
  { de: "wertlos", ku: "bê nirx / bê qîmet", c: "adjectives" },
  { de: "praktisch", ku: "bi kar / kêrhatî", c: "adjectives" },
  { de: "nutzlos", ku: "bêkêr / bêfayîde", c: "adjectives" },
  { de: "original", ku: "resen / eslî", c: "adjectives" },
  { de: "gefälscht", ku: "sexte / ne rast", c: "adjectives" },
  { de: "dauerhaft", ku: "berdewam / domdar", c: "adjectives" },
  { de: "vorübergehend", ku: "demkî / ji bo demekê", c: "adjectives" },
  { de: "dringend", ku: "acil / lezgîn", c: "adjectives" },
  { de: "gemütlich", ku: "xweş / rehet", c: "adjectives" },
  { de: "unbequem", ku: "nerehet / ne baş", c: "adjectives" },
  { de: "angemessen", ku: "li bar / li gor", c: "adjectives" },
  { de: "unpassend", ku: "ne li bar / ne guncan", c: "adjectives" },
  { de: "offensichtlich", ku: "diyar / eşkere", c: "adjectives" },
  { de: "geheim", ku: "veşartî / razdar", c: "adjectives" },
  { de: "öffentlich", ku: "giştî / eşkere", c: "adjectives" },
  { de: "privat", ku: "taybet / kesane", c: "adjectives" },
  { de: "natürlich (Produkt)", ku: "xwezayî / siruştî", c: "adjectives" },
  { de: "künstlich", ku: "çêkirî / destçêkirî", c: "adjectives" },
  { de: "modern", ku: "modern / nûjen", c: "adjectives" },
  { de: "altmodisch", ku: "kevneşopî / yê berê", c: "adjectives" },
  { de: "typisch", ku: "tîpîk / asayî", c: "adjectives" },
  { de: "seltsam", ku: "ecêb / xerîb", c: "adjectives" },

  // =============================================
  // PHRASES — New entries not in existing 163 phrases
  // =============================================

  // Deeper conversation
  { de: "Was machst du beruflich?", ku: "Tu çi karî dikî?", c: "phrases", t: 1 },
  { de: "Ich bin Ingenieur", ku: "Ez endezyar im / Ez muhendis im", c: "phrases", t: 1 },
  { de: "Ich bin Arzt", ku: "Ez doktor im / Ez bijîşk im", c: "phrases", t: 1 },
  { de: "Ich bin Geschäftsmann", ku: "Ez bazirgan im", c: "phrases", t: 1 },
  { de: "Wo hast du studiert?", ku: "Tu li kwê xwendiye?", c: "phrases", t: 1 },
  { de: "Ich studiere an der Universität", ku: "Ez li zanîngehê dixwînim", c: "phrases", t: 1 },
  { de: "Was sind deine Hobbys?", ku: "Hobiyên te çi ne?", c: "phrases", t: 1 },
  { de: "Ich reise gerne", ku: "Ez hez dikim rêwîtî bikim", c: "phrases", t: 1 },
  { de: "Erzähl mir von deiner Familie", ku: "Ji min re li ser malbata xwe bibêje", c: "phrases", t: 1 },
  { de: "Wie viele Geschwister hast du?", ku: "Çend xwişk û birayên te hene?", c: "phrases", t: 1 },

  // Expressing deeper opinions
  { de: "Ich finde das interessant", ku: "Ev li ba min balkêş e", c: "phrases", t: 1 },
  { de: "Das ist langweilig", ku: "Ev bêzar e / Ev acizkar e", c: "phrases", t: 1 },
  { de: "Ich bin überrascht", ku: "Ez şaşmayî mam / Ez ecêb mam", c: "phrases", t: 1 },
  { de: "Das ist unglaublich", ku: "Ev ne bawer e / Ev ecêb e", c: "phrases", t: 1 },
  { de: "Ganz ehrlich...", ku: "Bi rastî ...", c: "phrases", t: 1 },
  { de: "Soweit ich weiss", ku: "Bi qasî ku ez dizanim", c: "phrases", t: 1 },
  { de: "Lass mich nachdenken", ku: "Bihêle ez bifikrim", c: "phrases", t: 1 },
  { de: "Das kommt darauf an", ku: "Ew bi ... ve girêdayî ye", c: "phrases", t: 1 },
  { de: "Das spielt keine Rolle", ku: "Ew ne girîng e / Ferq nake", c: "phrases", t: 1 },
  { de: "Ich habe keine Ahnung", ku: "Qet nizanim / Tu hayê min ji tune", c: "phrases", t: 1 },

  // At the doctor (new entries)
  { de: "Mein Kopf tut weh", ku: "Serê min diêşe", c: "phrases", t: 1 },
  { de: "Mein Bauch tut weh", ku: "Zikê min diêşe", c: "phrases", t: 1 },
  { de: "Mein Rücken schmerzt", ku: "Piştê min êş dike", c: "phrases", t: 1 },
  { de: "Mein Zahn tut weh", ku: "Diranê min diêşe", c: "phrases", t: 1 },
  { de: "Mein Hals tut weh", ku: "Qirika min diêşe", c: "phrases", t: 1 },
  { de: "Ich habe Fieber", ku: "Taya min heye / Ez germ im", c: "phrases", t: 1 },
  { de: "Ich habe Durchfall", ku: "Zikê min diçe / Zikêşa min heye", c: "phrases", t: 1 },
  { de: "Mir ist schwindelig", ku: "Serê min dizîvire / Sergedan e li min", c: "phrases", t: 1 },
  { de: "Ich habe mich verbrannt", ku: "Ez şewitîm", c: "phrases", t: 1 },
  { de: "Ich habe mich geschnitten", ku: "Ez birîn bûm / Destê min hat birîn", c: "phrases", t: 1 },
  { de: "Ich brauche ein Medikament", ku: "Pêdiviya min bi dermanê heye", c: "phrases", t: 1 },
  { de: "Wie oft soll ich es nehmen?", ku: "Çend caran divê ez vî bixwim?", c: "phrases", t: 1 },
  { de: "Vor oder nach dem Essen?", ku: "Berî xwarinê yan piştî xwarinê?", c: "phrases", t: 1 },
  { de: "Ist es ernst?", ku: "Rewş giran e? / Xeternak e?", c: "phrases", t: 1 },
  { de: "Gute Besserung!", ku: "Xwedê şîfa bide te! / Zû baş bibî!", c: "phrases", t: 1 },

  // Shopping & market (new)
  { de: "Kann ich das umtauschen?", ku: "Ez dikarim vê biguhêzim?", c: "phrases", t: 1 },
  { de: "Das passt mir nicht", ku: "Ev li min nayê", c: "phrases", t: 1 },
  { de: "Gibt es das auch in Rot?", ku: "Ev di rengê sor de jî heye?", c: "phrases", t: 1 },
  { de: "Das ist ein guter Preis", ku: "Ev bihayek baş e", c: "phrases", t: 1 },
  { de: "Ich möchte bar bezahlen", ku: "Ez dixwazim bi drav bidim", c: "phrases", t: 1 },
  { de: "Wann öffnet der Laden?", ku: "Dikan kengî vedibe?", c: "phrases", t: 1 },
  { de: "Wo ist das Einkaufszentrum?", ku: "Navenda kirrînê li kwê ye?", c: "phrases", t: 1 },
  { de: "Ist das handgemacht?", ku: "Ev destçêkirî ye?", c: "phrases", t: 1 },
  { de: "Aus was ist das gemacht?", ku: "Ev ji çi çêkirî ye?", c: "phrases", t: 1 },

  // Travel & transport (new)
  { de: "Wie weit ist es bis...?", ku: "Heta ... çiqas dûr e?", c: "phrases", t: 1 },
  { de: "Gibt es einen direkten Weg?", ku: "Rêyek rasterast heye?", c: "phrases", t: 1 },
  { de: "Wo kann ich ein Auto mieten?", ku: "Ez li kwê dikarim erebeyekê bi kirê bigirim?", c: "phrases", t: 1 },
  { de: "Die Strasse ist gesperrt", ku: "Rê girtî ye", c: "phrases", t: 1 },
  { de: "Gibt es eine Umleitung?", ku: "Rêyek din heye?", c: "phrases", t: 1 },
  { de: "Wir haben eine Panne", ku: "Erebeya me xirab bû", c: "phrases", t: 1 },
  { de: "Wo ist die nächste Tankstelle?", ku: "Stasyona benzînê ya herî nêzîk li kwê ye?", c: "phrases", t: 1 },
  { de: "Volltanken bitte", ku: "Tije bike zehmet nebe", c: "phrases", t: 1 },
  { de: "Wann kommt der Flug an?", ku: "Balafir kengî datîne?", c: "phrases", t: 1 },
  { de: "Mein Flug hat Verspätung", ku: "Balafire min dereng e", c: "phrases", t: 1 },

  // Weather conversation (new)
  { de: "Wie wird das Wetter morgen?", ku: "Hewa sibê çawa dibe?", c: "phrases", t: 1 },
  { de: "Es ist sehr schwül heute", ku: "Îro gelek germşil e", c: "phrases", t: 1 },
  { de: "Sieht nach Regen aus", ku: "Wek ku baran bê xuya dike", c: "phrases", t: 1 },
  { de: "Der Sommer in Kurdistan ist heiss", ku: "Havîna Kurdistanê germ e", c: "phrases", t: 1 },
  { de: "Der Winter ist kalt in den Bergen", ku: "Zivistana çiyan gelek sar e", c: "phrases", t: 1 },

  // Kurdish proverbs & wisdom (pend û gotinên pêşiyan)
  { de: "Einheit ist Stärke", ku: "Yekîtî hêz e", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Wissen ist Licht", ku: "Zanîn ronahî ye", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Der Gast ist Gast Gottes", ku: "Mêvan mêvanê Xwedê ye", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Nicht alles was glänzt ist Gold", ku: "Ne her tiştê ku dibiriqe zêr e", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Der Apfel fällt nicht weit vom Stamm", ku: "Dar ji kokê xwe dûr nakeve", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Reden ist Silber, Schweigen ist Gold", ku: "Axaftin zîv e, bêdengî zêr e", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Ein wahrer Freund zeigt sich in der Not", ku: "Hevalê rast di tengasiyê de xuya dibe", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Ehre ist mehr wert als Gold", ku: "Namûs ji zêr girantir e", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Wer nicht arbeitet, soll nicht essen", ku: "Yê ku naxebite, bila nexwe", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Die Zunge hat keine Knochen", ku: "Ziman hestî tune ye", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Tropfen für Tropfen wird ein See", ku: "Dilopê bi dilopê gol dibe", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Wer früh aufsteht, dem hilft Gott", ku: "Yê ku zû radibe, Xwedê jê re xêrê dike", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Tue Gutes und wirf es ins Meer", ku: "Qenciyê bike bavêje deryayê", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Wer eine Grube gräbt, fällt selbst hinein", ku: "Kê çal ji bo kesekî din kola, ew bi xwe dikeve tê de", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Der Hund bellt, die Karawane zieht weiter", ku: "Kûçik diqîre, karwan derbas dibe", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Eile mit Weile", ku: "Bi sebir bi ser dikevî", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Übung macht den Meister", ku: "Pratîk osta çêdike", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Ohne Fleiss kein Preis", ku: "Bê xebatê serkeftin tune ye", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Der Mund des Menschen ist sein Verderben", ku: "Devê mirovî dijminê wî ye", c: "phrases", t: 1, n: "Sprichwort" },
  { de: "Eine Hand wäscht die andere", ku: "Dest destê din dişo", c: "phrases", t: 1, n: "Sprichwort" },

  // Everyday Kurdish expressions
  { de: "Sei willkommen!", ku: "Bi xêr hatî! / Serhati!", c: "phrases", t: 1 },
  { de: "Lass dir Zeit", ku: "Hêdî hêdî / Bê lez", c: "phrases", t: 1 },
  { de: "Lass uns Tee trinken", ku: "Were em çay vexwin", c: "phrases", t: 1 },
  { de: "Bitte setz dich", ku: "Zehmet nebe rûne", c: "phrases", t: 1 },
  { de: "Fühl dich wie zu Hause", ku: "Xwe wek li mala xwe bibîne", c: "phrases", t: 1 },
  { de: "Pass auf dich auf", ku: "Hay ji xwe hebe / Xwe biparêze", c: "phrases", t: 1 },
  { de: "Gute Reise!", ku: "Rêya te bi xêr! / Rê li ber te vekirî be!", c: "phrases", t: 1 },
  { de: "Viel Erfolg!", ku: "Serkeftina te bi xêr! / Biser be!", c: "phrases", t: 1 },
  { de: "Herzlichen Glückwunsch!", ku: "Pîroz be! / Bimbarek be!", c: "phrases", t: 1 },
  { de: "Frohe Feiertage!", ku: "Cejna te pîroz be!", c: "phrases", t: 1 },
  { de: "Gott sei mit dir", ku: "Xwedê li gel te be", c: "phrases", t: 1 },
  { de: "Ich vermisse Kurdistan", ku: "Bêriya Kurdistanê li min e", c: "phrases", t: 1 },
  { de: "Die Berge sind wunderschön", ku: "Çiya gelek bedew in", c: "phrases", t: 1 },
  { de: "Wir kommen wieder!", ku: "Em ê dîsa bên!", c: "phrases", t: 1 },
];
