import { createClient } from '@libsql/client';
import { readFileSync } from 'fs';
import { resolve } from 'path';

// Load env manually (no dotenv dependency)
function loadEnv(filePath) {
  try {
    const content = readFileSync(filePath, 'utf-8');
    for (const line of content.split('\n')) {
      const match = line.match(/^([^#=]+)=(.*)$/);
      if (match) {
        const key = match[1].trim();
        let val = match[2].trim();
        if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
          val = val.slice(1, -1);
        }
        if (!process.env[key]) process.env[key] = val;
      }
    }
  } catch { /* file not found */ }
}
loadEnv(resolve(process.cwd(), '.env.local'));
loadEnv(resolve(process.cwd(), '.env'));

const db = createClient({
  url: process.env.TURSO_DATABASE_URL,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

// New words to add — Kurdisch Badini (Kurmanci)
const NEW_WORDS = [
  // === COLORS (currently 15) ===
  { de: "rosa", ku: "Pembe / Gularî", c: "colors" },
  { de: "lila", ku: "Binefşî / Mor", c: "colors" },
  { de: "orange", ku: "Pirteqalî", c: "colors" },
  { de: "beige", ku: "Bej / Bor", c: "colors" },
  { de: "türkis", ku: "Şînê deryayê", c: "colors" },
  { de: "silber", ku: "Zîv / Zîvreng", c: "colors" },
  { de: "gold", ku: "Zêr / Zêrreng", c: "colors" },
  { de: "dunkelblau", ku: "Şîntarî", c: "colors" },
  { de: "hellgrün", ku: "Keska ronî", c: "colors" },
  { de: "dunkelrot", ku: "Sora tarî", c: "colors" },
  { de: "bunt", ku: "Rengreng / Pirr reng", c: "colors" },
  { de: "hell", ku: "Ronî / Ronayî", c: "colors" },
  { de: "dunkel", ku: "Tarî", c: "colors" },
  { de: "farblos", ku: "Bêreng", c: "colors" },
  { de: "cremefarbig", ku: "Şîrî / Kremî", c: "colors" },

  // === NATURE (currently 21) ===
  { de: "Fluss", ku: "Ro / Çem", c: "nature" },
  { de: "See", ku: "Gol", c: "nature" },
  { de: "Meer", ku: "Derya / Behr", c: "nature" },
  { de: "Wald", ku: "Daristan / Meşe", c: "nature" },
  { de: "Wiese", ku: "Mêrg / Çîmen", c: "nature" },
  { de: "Feld", ku: "Zevî / Kêlge", c: "nature" },
  { de: "Hügel", ku: "Gir / Tepik", c: "nature" },
  { de: "Tal", ku: "Gelî / Newal", c: "nature" },
  { de: "Quelle", ku: "Kanî / Çavkanî", c: "nature" },
  { de: "Wasserfall", ku: "Şelale / Avhelav", c: "nature" },
  { de: "Erdbeben", ku: "Bûmelerze / Erdhej", c: "nature" },
  { de: "Vulkan", ku: "Volkan / Çiyayê agirî", c: "nature" },
  { de: "Wüste", ku: "Çol / Beyaban", c: "nature" },
  { de: "Insel", ku: "Girav / Ada", c: "nature" },
  { de: "Ozean", ku: "Okyanûs", c: "nature" },
  { de: "Strand", ku: "Kenarê deryayê / Plaj", c: "nature" },
  { de: "Stein", ku: "Kevir / Ber", c: "nature" },
  { de: "Sand", ku: "Qûm / Xîz", c: "nature" },
  { de: "Erde", ku: "Erd / Ax", c: "nature" },
  { de: "Staub", ku: "Toz / Xwelî", c: "nature" },
  { de: "Schlamm", ku: "Herî / Qûr", c: "nature" },
  { de: "Eis", ku: "Qeşa / Cemedanî", c: "nature" },
  { de: "Schnee", ku: "Berf", c: "nature" },
  { de: "Regen", ku: "Baran", c: "nature" },
  { de: "Donner", ku: "Birûsk / Ewrreş", c: "nature" },
  { de: "Blitz", ku: "Birûsk", c: "nature" },
  { de: "Regenbogen", ku: "Keskesor / Qozeqeza", c: "nature" },
  { de: "Pflanze", ku: "Nebat / Riwek", c: "nature" },
  { de: "Blume", ku: "Gul / Kulîlk", c: "nature" },
  { de: "Rose", ku: "Gul", c: "nature" },
  { de: "Gras", ku: "Giya / Çîmen", c: "nature" },
  { de: "Blatt", ku: "Pelg / Berg", c: "nature" },
  { de: "Ast", ku: "Çiq / Liq", c: "nature" },
  { de: "Wurzel", ku: "Reh / Rîşe", c: "nature" },
  { de: "Samen", ku: "Tov / Fîşte", c: "nature" },
  { de: "Ernte", ku: "Dirûn / Berhevkirin", c: "nature" },

  // === ANIMALS (currently 23) ===
  { de: "Pferd", ku: "Hesp / Esb", c: "animals" },
  { de: "Esel", ku: "Ker", c: "animals" },
  { de: "Kuh", ku: "Mange / Çêlek", c: "animals" },
  { de: "Schaf", ku: "Mî / Pez", c: "animals" },
  { de: "Ziege", ku: "Bizin", c: "animals" },
  { de: "Huhn", ku: "Mirîşk", c: "animals" },
  { de: "Hahn", ku: "Dîk", c: "animals" },
  { de: "Ente", ku: "Werdek / Miravî", c: "animals" },
  { de: "Gans", ku: "Qaz", c: "animals" },
  { de: "Fisch", ku: "Masî", c: "animals" },
  { de: "Schlange", ku: "Mar", c: "animals" },
  { de: "Adler", ku: "Helo / Eylo", c: "animals" },
  { de: "Taube", ku: "Kevok / Kotir", c: "animals" },
  { de: "Schmetterling", ku: "Perîpelîsk / Firfire", c: "animals" },
  { de: "Biene", ku: "Hingivîn / Mêşhingivîn", c: "animals" },
  { de: "Ameise", ku: "Mûrî / Mêrûk", c: "animals" },
  { de: "Fliege", ku: "Mêş", c: "animals" },
  { de: "Mücke", ku: "Mêşa tatûrê / Tatûre", c: "animals" },
  { de: "Spinne", ku: "Tevnpîrk / Daretevnê", c: "animals" },
  { de: "Wolf", ku: "Gur", c: "animals" },
  { de: "Fuchs", ku: "Rovî", c: "animals" },
  { de: "Bär", ku: "Hirç", c: "animals" },
  { de: "Löwe", ku: "Şêr", c: "animals" },
  { de: "Tiger", ku: "Piling / Bebir", c: "animals" },
  { de: "Kamel", ku: "Hêştir / Deve", c: "animals" },
  { de: "Elefant", ku: "Fîl", c: "animals" },
  { de: "Affe", ku: "Meymûn", c: "animals" },
  { de: "Schildkröte", ku: "Kûsî / Kevjal", c: "animals" },
  { de: "Frosch", ku: "Beq", c: "animals" },
  { de: "Kaninchen", ku: "Kêroşk / Xirnîç", c: "animals" },
  { de: "Maus", ku: "Mişk", c: "animals" },
  { de: "Ratte", ku: "Cirçirk / Mişkê gewre", c: "animals" },
  { de: "Stier", ku: "Ga / Cûga", c: "animals" },
  { de: "Lamm", ku: "Berx", c: "animals" },
  { de: "Kalb", ku: "Golik", c: "animals" },

  // === BODY (currently 26) ===
  { de: "Stirn", ku: "Enî", c: "body" },
  { de: "Wange", ku: "Gep / Rû", c: "body" },
  { de: "Kinn", ku: "Çenê / Zenî", c: "body" },
  { de: "Lippe", ku: "Lêv", c: "body" },
  { de: "Zunge", ku: "Ziman", c: "body" },
  { de: "Zahn", ku: "Didan / Diran", c: "body" },
  { de: "Hals", ku: "Stû / Gewrî", c: "body" },
  { de: "Schulter", ku: "Mil / Şan", c: "body" },
  { de: "Arm", ku: "Bazin / Dest", c: "body" },
  { de: "Ellbogen", ku: "Enîşk", c: "body" },
  { de: "Handgelenk", ku: "Dest / Zend", c: "body" },
  { de: "Daumen", ku: "Tiliya gewre / Qamişk", c: "body" },
  { de: "Fingernagel", ku: "Neynûk", c: "body" },
  { de: "Brust", ku: "Sing / Ber", c: "body" },
  { de: "Rücken", ku: "Piştî / Pişt", c: "body" },
  { de: "Bauch", ku: "Zik / Wîde", c: "body" },
  { de: "Hüfte", ku: "Hember / Navteng", c: "body" },
  { de: "Knie", ku: "Çok", c: "body" },
  { de: "Knöchel", ku: "Gopalka pê / Qolç", c: "body" },
  { de: "Ferse", ku: "Pêşî / Paşpê", c: "body" },
  { de: "Zehe", ku: "Tiliya pê", c: "body" },
  { de: "Haut", ku: "Çerm / Pîst", c: "body" },
  { de: "Knochen", ku: "Hestî", c: "body" },
  { de: "Blut", ku: "Xwîn", c: "body" },
  { de: "Herz", ku: "Dil", c: "body" },
  { de: "Lunge", ku: "Pişk / Sîyê", c: "body" },
  { de: "Gehirn", ku: "Mêjî / Mejî", c: "body" },
  { de: "Muskel", ku: "Masûlke / Ezele", c: "body" },
  { de: "Augenbraue", ku: "Birû / Birû", c: "body" },
  { de: "Wimper", ku: "Birjang / Bijang", c: "body" },

  // === FAMILY (currently 28) ===
  { de: "Grosseltern", ku: "Bapîr û Dapîr", c: "family" },
  { de: "Urgrossvater", ku: "Bapîrê bapîr", c: "family" },
  { de: "Urgrossmutter", ku: "Dapîra dapîrê", c: "family" },
  { de: "Schwiegervater", ku: "Xezûr", c: "family" },
  { de: "Schwiegermutter", ku: "Xesû", c: "family" },
  { de: "Schwiegersohn", ku: "Zava", c: "family" },
  { de: "Schwiegertochter", ku: "Bûk", c: "family" },
  { de: "Schwager", ku: "Hevzava / Baca", c: "family" },
  { de: "Schwägerin", ku: "Jinbira / Hevjin", c: "family" },
  { de: "Neffe", ku: "Birazî (kur)", c: "family" },
  { de: "Nichte", ku: "Birazî (keç)", c: "family" },
  { de: "Waise", ku: "Sêwî / Yetîm", c: "family" },
  { de: "Verlobte/r", ku: "Destgirtî / Nîşanlî", c: "family" },
  { de: "Zwilling", ku: "Cêwî / Dûçik", c: "family" },
  { de: "Verwandter", ku: "Xizm / Malbatî", c: "family" },

  // === GREETINGS (currently 27) ===
  { de: "Herzlich willkommen", ku: "Bi xêr hatî", c: "greetings" },
  { de: "Schönen Abend", ku: "Êvara te xweş", c: "greetings" },
  { de: "Gute Besserung", ku: "Xwedê şîfa bide te", c: "greetings" },
  { de: "Herzlichen Glückwunsch", ku: "Pîroz be", c: "greetings" },
  { de: "Alles Gute zum Geburtstag", ku: "Rojbûna te pîroz be", c: "greetings" },
  { de: "Frohes neues Jahr", ku: "Sala nû pîroz be", c: "greetings" },
  { de: "Frohe Feiertage", ku: "Cejna te pîroz be", c: "greetings" },
  { de: "Gute Reise", ku: "Rêya te xweş be", c: "greetings" },
  { de: "Viel Erfolg", ku: "Serkeftin", c: "greetings" },
  { de: "Viel Glück", ku: "Bextê te hebe", c: "greetings" },
  { de: "Pass auf dich auf", ku: "Xwe biparêze", c: "greetings" },
  { de: "Wir vermissen dich", ku: "Em bêriya te dikin", c: "greetings" },
  { de: "Ich bin stolz auf dich", ku: "Ez serbilind im bi te", c: "greetings" },

  // === NUMBERS (currently 28) — add ordinals and larger numbers ===
  { de: "dreissig", ku: "sî", c: "numbers" },
  { de: "vierzig", ku: "çil", c: "numbers" },
  { de: "fünfzig", ku: "pêncî", c: "numbers" },
  { de: "sechzig", ku: "şêst", c: "numbers" },
  { de: "siebzig", ku: "heftê", c: "numbers" },
  { de: "achtzig", ku: "heştê", c: "numbers" },
  { de: "neunzig", ku: "not / nod", c: "numbers" },
  { de: "hundert", ku: "sed", c: "numbers" },
  { de: "tausend", ku: "hezar", c: "numbers" },
  { de: "Million", ku: "mîlyon", c: "numbers" },
  { de: "erster", ku: "yekemîn / ewil", c: "numbers" },
  { de: "zweiter", ku: "duwemîn / dido", c: "numbers" },
  { de: "dritter", ku: "sêyemîn", c: "numbers" },
  { de: "letzter", ku: "dawîn / paşîn", c: "numbers" },
  { de: "Hälfte", ku: "nîv", c: "numbers" },
  { de: "Viertel", ku: "çarêk", c: "numbers" },
  { de: "Drittel", ku: "sêyek", c: "numbers" },
  { de: "Doppel", ku: "ducar / duqat", c: "numbers" },
  { de: "Paar", ku: "cot / jift", c: "numbers" },
  { de: "einige", ku: "hindek / çendek", c: "numbers" },
  { de: "viele", ku: "gelek / pirr", c: "numbers" },
  { de: "wenige", ku: "hindik / kêm", c: "numbers" },

  // === WEATHER (currently 35) ===
  { de: "Nebel", ku: "Mij / Dûman", c: "weather" },
  { de: "Frost", ku: "Sar / Cemidî", c: "weather" },
  { de: "Hagel", ku: "Teyrok / Zîpik", c: "weather" },
  { de: "Gewitter", ku: "Bahoz / Tofan", c: "weather" },
  { de: "Sturm", ku: "Bahoz / Firtûne", c: "weather" },
  { de: "Orkan", ku: "Bahoza mezin", c: "weather" },
  { de: "Hitzewelle", ku: "Pêla germê", c: "weather" },
  { de: "Trockenheit", ku: "Zuhabûn / Wişkahî", c: "weather" },
  { de: "Überschwemmung", ku: "Lehî / Lêv", c: "weather" },
  { de: "Sonnenaufgang", ku: "Berbanga rojê / Rojhilatin", c: "weather" },
  { de: "Sonnenuntergang", ku: "Rojavabûn / Rojava", c: "weather" },
  { de: "Temperatur", ku: "Germahî / Asta germê", c: "weather" },
  { de: "Grad", ku: "Derece / Pîv", c: "weather" },
  { de: "schwül", ku: "Şil û germ", c: "weather" },
  { de: "mild", ku: "Nerm / Hênik", c: "weather" },
  { de: "frisch", ku: "Hênik / Teze", c: "weather" },
  { de: "trocken", ku: "Wişk / Zuha", c: "weather" },
  { de: "feucht", ku: "Şil / Ter", c: "weather" },
  { de: "heiter", ku: "Vekirî / Zelal", c: "weather" },
  { de: "bewölkt", ku: "Ewr / Hewrî", c: "weather" },

  // === SHOPPING (currently 41) ===
  { de: "Kasse", ku: "Kasa / Sandûq", c: "shopping" },
  { de: "Quittung", ku: "Fîş / Wesîqe", c: "shopping" },
  { de: "Einkaufswagen", ku: "Erebeya bazêrê", c: "shopping" },
  { de: "Regal", ku: "Ref / Dolap", c: "shopping" },
  { de: "Sonderangebot", ku: "Pêşkêşî taybet", c: "shopping" },
  { de: "Verpackung", ku: "Pakêt / Pêçan", c: "shopping" },
  { de: "Tüte", ku: "Kîse / Tûrik", c: "shopping" },
  { de: "Marke", ku: "Marka / Nîşan", c: "shopping" },
  { de: "Grösse", ku: "Mezinahî / Qebare", c: "shopping" },
  { de: "Umtausch", ku: "Guhertin / Veguhertin", c: "shopping" },
  { de: "Garantie", ku: "Garantî / Misoger", c: "shopping" },
  { de: "online bestellen", ku: "li ser înternetê spartin", c: "shopping" },
  { de: "bezahlen", ku: "paredayîn / dayîn", c: "shopping" },
  { de: "Bargeld", ku: "Pereyê destan / Neqd", c: "shopping" },
  { de: "Kreditkarte", ku: "Karta krediyê", c: "shopping" },

  // === CULTURE (currently 48) ===
  { de: "Newroz", ku: "Newroz", c: "culture" },
  { de: "Volkstanz", ku: "Govend / Helperkê", c: "culture" },
  { de: "Märchen", ku: "Çîrok / Hîkaye", c: "culture" },
  { de: "Legende", ku: "Efsane / Destane", c: "culture" },
  { de: "Sprichwort", ku: "Gotinên pêşiyan / Mesele", c: "culture" },
  { de: "Gastfreundschaft", ku: "Mêvanperwerî", c: "culture" },
  { de: "Hochzeit", ku: "Dawet / Zewac", c: "culture" },
  { de: "Tracht", ku: "Cilê kurdî / Cilê kevneşopî", c: "culture" },
  { de: "Handwerk", ku: "Huner / Pîşe", c: "culture" },
  { de: "Teppich", ku: "Xalîçe / Bermal", c: "culture" },
  { de: "Keramik", ku: "Seramîk / Kûze", c: "culture" },
  { de: "Dichtung", ku: "Helbestî / Şêr", c: "culture" },
  { de: "Dichter", ku: "Helbestvan / Şaîr", c: "culture" },
  { de: "Erzähler", ku: "Çîrokbêj / Dengbêj", c: "culture" },
  { de: "Erbe", ku: "Mîras / Wêris", c: "culture" },

  // === VERBS — more common verbs ===
  { de: "schlafen", ku: "razandin / xew kirin", c: "verbs" },
  { de: "aufwachen", ku: "rabûn / hişyar bûn", c: "verbs" },
  { de: "waschen", ku: "şûştin", c: "verbs" },
  { de: "kochen", ku: "çêkirin / pijandin", c: "verbs" },
  { de: "schneiden", ku: "birîn / qut kirin", c: "verbs" },
  { de: "nähen", ku: "dirûtin", c: "verbs" },
  { de: "pflanzen", ku: "çandin", c: "verbs" },
  { de: "ernten", ku: "dirûn / berhevkirin", c: "verbs" },
  { de: "bauen", ku: "avakirin / çêkirin", c: "verbs" },
  { de: "reparieren", ku: "tamîr kirin / çêkirin", c: "verbs" },
  { de: "zerbrechen", ku: "şikandin / perçe kirin", c: "verbs" },
  { de: "werfen", ku: "avêtin", c: "verbs" },
  { de: "fangen", ku: "girtin / desteserkirin", c: "verbs" },
  { de: "klettern", ku: "hilkişîn / rabûn", c: "verbs" },
  { de: "schwimmen", ku: "avjenî kirin / melê kirin", c: "verbs" },
  { de: "tauchen", ku: "binav bûn / xwe nav avê kirin", c: "verbs" },
  { de: "fliegen", ku: "firîn", c: "verbs" },
  { de: "fallen", ku: "ketin", c: "verbs" },
  { de: "stehen", ku: "rawestîn / sekinîn", c: "verbs" },
  { de: "sitzen", ku: "rûniştin", c: "verbs" },
  { de: "liegen", ku: "razîn / xwe dirêj kirin", c: "verbs" },
  { de: "rennen", ku: "bezîn / revîn", c: "verbs" },
  { de: "springen", ku: "bazdan", c: "verbs" },
  { de: "tanzen", ku: "reqisîn / govend girtin", c: "verbs" },
  { de: "singen", ku: "stiran gotin / strandin", c: "verbs" },
  { de: "weinen", ku: "girîn", c: "verbs" },
  { de: "lachen", ku: "kenîn", c: "verbs" },
  { de: "schreien", ku: "qîrîn", c: "verbs" },
  { de: "flüstern", ku: "pistpistin / bi dizî gotin", c: "verbs" },
  { de: "küssen", ku: "ramûsan kirin / maç kirin", c: "verbs" },
  { de: "umarmen", ku: "hembêz kirin", c: "verbs" },
  { de: "vertrauen", ku: "pişt girtin / bawer kirin", c: "verbs" },
  { de: "zweifeln", ku: "dudilî bûn / guman kirin", c: "verbs" },
  { de: "träumen", ku: "xewn dîtin", c: "verbs" },
  { de: "vergessen", ku: "ji bîr kirin", c: "verbs" },
  { de: "sich erinnern", ku: "bîr kirin / tê bîra min", c: "verbs" },

  // === ADJECTIVES — more descriptors ===
  { de: "mutig", ku: "wêrek / mêrxas", c: "adjectives" },
  { de: "feige", ku: "tirsonek / cizîrî", c: "adjectives" },
  { de: "ehrlich", ku: "rast / durustkar", c: "adjectives" },
  { de: "unehrlich", ku: "derewîn / derew", c: "adjectives" },
  { de: "fleissig", ku: "jêhatî / kedkar", c: "adjectives" },
  { de: "faul", ku: "tiral / bêkar", c: "adjectives" },
  { de: "geduldig", ku: "sebir / birîvar", c: "adjectives" },
  { de: "ungeduldig", ku: "bêsebir / bêbîr", c: "adjectives" },
  { de: "höflich", ku: "birêz / rêzdar", c: "adjectives" },
  { de: "unhöflich", ku: "bêrêz / bêedeb", c: "adjectives" },
  { de: "neugierig", ku: "meraqdar / pirrsyarker", c: "adjectives" },
  { de: "stolz", ku: "serbilind / qure", c: "adjectives" },
  { de: "bescheiden", ku: "nermîn / kêmîs", c: "adjectives" },
  { de: "eifersüchtig", ku: "çavnebar / hevsûdî", c: "adjectives" },
  { de: "tief", ku: "kûr / qûl", c: "adjectives" },
  { de: "flach", ku: "sist / deşt", c: "adjectives" },
  { de: "scharf", ku: "tûj / tîj", c: "adjectives" },
  { de: "stumpf", ku: "kirêt / kût", c: "adjectives" },
  { de: "weich", ku: "nerm / hêşîn", c: "adjectives" },
  { de: "hart", ku: "hişk / req", c: "adjectives" },
  { de: "glatt", ku: "lûs / zeliqî", c: "adjectives" },
  { de: "rau", ku: "qeraş / hovane", c: "adjectives" },
  { de: "feucht", ku: "şil / ter", c: "adjectives" },
  { de: "bitter", ku: "tal", c: "adjectives" },
  { de: "süss", ku: "şîrîn", c: "adjectives" },
  { de: "sauer", ku: "tirş", c: "adjectives" },
  { de: "salzig", ku: "şor", c: "adjectives" },
  { de: "giftig", ku: "jehrî / jehrîn", c: "adjectives" },
  { de: "lebendig", ku: "zindî / sax", c: "adjectives" },
  { de: "tot", ku: "mirî", c: "adjectives" },

  // === FOOD — more dishes and ingredients ===
  { de: "Reis", ku: "Birnic / Pirinc", c: "food" },
  { de: "Nudeln", ku: "Reşte / Makarna", c: "food" },
  { de: "Suppe", ku: "Şorbe / Avik", c: "food" },
  { de: "Salat", ku: "Salate / Zeleqe", c: "food" },
  { de: "Gewürz", ku: "Bîhar / Tewaze", c: "food" },
  { de: "Salz", ku: "Xwê", c: "food" },
  { de: "Pfeffer", ku: "Bîber / Îsot", c: "food" },
  { de: "Knoblauch", ku: "Sîr", c: "food" },
  { de: "Zwiebel", ku: "Pîvaz", c: "food" },
  { de: "Kartoffel", ku: "Patate / Kartol", c: "food" },
  { de: "Tomate", ku: "Firingî / Bacanê sor", c: "food" },
  { de: "Gurke", ku: "Xiyar", c: "food" },
  { de: "Karotte", ku: "Gêzer", c: "food" },
  { de: "Aubergine", ku: "Bacan", c: "food" },
  { de: "Paprika", ku: "Bîbera şîrîn", c: "food" },
  { de: "Apfel", ku: "Sêv", c: "food" },
  { de: "Birne", ku: "Hirmî", c: "food" },
  { de: "Traube", ku: "Tirî", c: "food" },
  { de: "Wassermelone", ku: "Zebeş / Şûtî", c: "food" },
  { de: "Feige", ku: "Hêjîr", c: "food" },
  { de: "Walnuss", ku: "Gûz", c: "food" },
  { de: "Mandel", ku: "Behîv / Badem", c: "food" },
  { de: "Honig", ku: "Hingiv", c: "food" },
  { de: "Joghurt", ku: "Mast", c: "food" },
  { de: "Käse", ku: "Penîr", c: "food" },
  { de: "Butter", ku: "Nîvişk / Rûn", c: "food" },
  { de: "Öl", ku: "Rûnê zeytûnê / Rûn", c: "food" },
  { de: "Mehl", ku: "Ard", c: "food" },
  { de: "Teig", ku: "Hevîr", c: "food" },
  { de: "Kuchen", ku: "Kêk / Kûlîçe", c: "food" },

  // === EMOTIONS — expand ===
  { de: "Angst", ku: "Tirs / Xof", c: "emotions" },
  { de: "Mut", ku: "Wêrekî / Cesaret", c: "emotions" },
  { de: "Hoffnung", ku: "Hêvî / Ûmîd", c: "emotions" },
  { de: "Verzweiflung", ku: "Bêhêvîtî / Bêçare", c: "emotions" },
  { de: "Zufriedenheit", ku: "Razîbûn / Qenayetî", c: "emotions" },
  { de: "Ärger", ku: "Hêrs / Xezeb", c: "emotions" },
  { de: "Überraschung", ku: "Ecêb / Şaşmayîn", c: "emotions" },
  { de: "Langeweile", ku: "Acizî / Bêzarî", c: "emotions" },
  { de: "Sehnsucht", ku: "Bêrî / Hesret", c: "emotions" },
  { de: "Mitgefühl", ku: "Dilsozî / Dilovanî", c: "emotions" },
  { de: "Scham", ku: "Şerm / Eyb", c: "emotions" },
  { de: "Stolz", ku: "Serbilindî / Qureyî", c: "emotions" },
  { de: "Neid", ku: "Çavnebarî / Hevsûdî", c: "emotions" },
  { de: "Dankbarkeit", ku: "Spasdarî / Şikir", c: "emotions" },
  { de: "Einsamkeit", ku: "Tenêtî / Bêkesî", c: "emotions" },

  // === PHRASES — more daily sentences ===
  { de: "Wo ist die Toilette?", ku: "Tiwalet li ku ye?", c: "phrases", t: 1 },
  { de: "Ich habe Hunger", ku: "Ez birçî me", c: "phrases", t: 1 },
  { de: "Ich habe Durst", ku: "Ez tî me", c: "phrases", t: 1 },
  { de: "Ich bin müde", ku: "Ez westiyayî me", c: "phrases", t: 1 },
  { de: "Können Sie mir helfen?", ku: "Tu dikarî alîkariya min bikî?", c: "phrases", t: 1 },
  { de: "Wie spät ist es?", ku: "Saet çend e?", c: "phrases", t: 1 },
  { de: "Was kostet das?", ku: "Ev bi çend e?", c: "phrases", t: 1 },
  { de: "Ich möchte bezahlen", ku: "Ez dixwazim bideym", c: "phrases", t: 1 },
  { de: "Sprechen Sie Deutsch?", ku: "Tu elman zanî?", c: "phrases", t: 1 },
  { de: "Ich komme aus Deutschland", ku: "Ez ji Almanya me", c: "phrases", t: 1 },
  { de: "Ich lerne Kurdisch", ku: "Ez kurdî hîn dibim", c: "phrases", t: 1 },
  { de: "Das schmeckt gut", ku: "Ev xweş e / Ev tam dike", c: "phrases", t: 1 },
  { de: "Ich liebe dich", ku: "Ez ji te hez dikim", c: "phrases", t: 1 },
  { de: "Mir geht es gut", ku: "Ez baş im", c: "phrases", t: 1 },
  { de: "Mir geht es nicht gut", ku: "Ez baş nînim / Halê min ne baş e", c: "phrases", t: 1 },
  { de: "Ich vermisse dich", ku: "Ez bêriya te dikim", c: "phrases", t: 1 },
  { de: "Keine Sorge", ku: "Xem nexwe / Netirse", c: "phrases", t: 1 },
  { de: "Es tut mir leid", ku: "Bibore / Mixabin", c: "phrases", t: 1 },
  { de: "Natürlich", ku: "Bê guman / Erê", c: "phrases", t: 1 },
  { de: "Vielleicht", ku: "Belkî / Dibe", c: "phrases", t: 1 },
  { de: "Bestimmt", ku: "Bê guman / Bêje", c: "phrases", t: 1 },
  { de: "Egal", ku: "Ne girîng e / Ferq nake", c: "phrases", t: 1 },
  { de: "Genau", ku: "Rast e / Tam wisa", c: "phrases", t: 1 },
  { de: "Komm her", ku: "Were vir", c: "phrases", t: 1 },
  { de: "Geh weg", ku: "Here / Dûr bikeve", c: "phrases", t: 1 },
  { de: "Setz dich", ku: "Rûne", c: "phrases", t: 1 },
  { de: "Steh auf", ku: "Rabe", c: "phrases", t: 1 },
  { de: "Sei ruhig", ku: "Bêdeng be / Hêdî be", c: "phrases", t: 1 },
  { de: "Warte", ku: "Bisekine / Raweste", c: "phrases", t: 1 },
  { de: "Beeil dich", ku: "Blez be / Zû be", c: "phrases", t: 1 },

  // === TECHNOLOGY — expand ===
  { de: "Passwort", ku: "Şîfre / Pêborîn", c: "technology" },
  { de: "Datei", ku: "Dosye / Pel", c: "technology" },
  { de: "herunterladen", ku: "daxistin / dawnload kirin", c: "technology" },
  { de: "hochladen", ku: "barkirin / upload kirin", c: "technology" },
  { de: "speichern", ku: "tomar kirin / parastin", c: "technology" },
  { de: "löschen", ku: "jêbirin / şandin", c: "technology" },
  { de: "kopieren", ku: "kopî kirin", c: "technology" },
  { de: "einfügen", ku: "lê kirin / tê xistin", c: "technology" },
  { de: "Bildschirm", ku: "Ekran / Dîmen", c: "technology" },
  { de: "Tastatur", ku: "Klavye / Bişkojk", c: "technology" },
  { de: "Drucker", ku: "Çapker / Prînter", c: "technology" },
  { de: "Kamera", ku: "Kamera / Wênegir", c: "technology" },
  { de: "Batterie", ku: "Pîl / Baterî", c: "technology" },
  { de: "laden (Akku)", ku: "şarj kirin", c: "technology" },
  { de: "Nachricht", ku: "Peyam / Mesaj", c: "technology" },
  { de: "Anruf", ku: "Bang / Telefon kirin", c: "technology" },
  { de: "Video", ku: "Vîdeo / Fîlm", c: "technology" },
  { de: "Foto", ku: "Wêne / Foto", c: "technology" },
  { de: "App", ku: "Sepan / Bernamek", c: "technology" },
  { de: "aktualisieren", ku: "nûkirin / update kirin", c: "technology" },

  // === SPORTS — expand ===
  { de: "Mannschaft", ku: "Tîm / Koma lîstikê", c: "sports" },
  { de: "Tor (Fussball)", ku: "Gol", c: "sports" },
  { de: "Schiedsrichter", ku: "Hakem / Dadger", c: "sports" },
  { de: "Gewinner", ku: "Serkeftî / Qazanç", c: "sports" },
  { de: "Verlierer", ku: "Têkçûyî / Windaker", c: "sports" },
  { de: "Meisterschaft", ku: "Şampiyona / Pêşbirk", c: "sports" },
  { de: "Training", ku: "Rahênan / Antrenman", c: "sports" },
  { de: "Stadion", ku: "Stadyûm / Qada lîstikê", c: "sports" },
  { de: "Medaille", ku: "Medalya / Mîdalya", c: "sports" },
  { de: "Rekord", ku: "Rekor / Tomarek", c: "sports" },
  { de: "Wandern", ku: "Meşîn / Gerîn", c: "sports" },
  { de: "Rad fahren", ku: "Bîsîklêt ajotin", c: "sports" },
  { de: "Boxen", ku: "Boks", c: "sports" },
  { de: "Ringen", ku: "Zorxane / Güreş", c: "sports" },
  { de: "Volleyball", ku: "Voleybol / Topê destê", c: "sports" },

  // === MUSIC — expand ===
  { de: "Instrument", ku: "Amûr / Enstrûman", c: "music" },
  { de: "Trommel", ku: "Dehol / Tebil", c: "music" },
  { de: "Flöte", ku: "Bilûr / Ney", c: "music" },
  { de: "Gitarre", ku: "Gîtar", c: "music" },
  { de: "Geige", ku: "Kemançe / Keman", c: "music" },
  { de: "Klavier", ku: "Piyano", c: "music" },
  { de: "Konzert", ku: "Konser / Aheng", c: "music" },
  { de: "Chor", ku: "Kor / Koma stranbêjan", c: "music" },
  { de: "Sänger", ku: "Stranbêj / Xwendevan", c: "music" },
  { de: "Sängerin", ku: "Stranbêj (jin)", c: "music" },
  { de: "Komponist", ku: "Bestekar / Ahengdar", c: "music" },
  { de: "Tanz", ku: "Reqis / Govend", c: "music" },
  { de: "Lautstärke", ku: "Dengê bilind / Deng", c: "music" },
  { de: "leise", ku: "hêdî / bi deng kêm", c: "music" },
  { de: "laut", ku: "bilind / bi deng", c: "music" },

  // === RELIGION — expand ===
  { de: "Moschee", ku: "Mizgeft / Camî", c: "religion" },
  { de: "Kirche", ku: "Dêr / Kilîse", c: "religion" },
  { de: "Tempel", ku: "Perestgeh / Ibadexane", c: "religion" },
  { de: "Friedhof", ku: "Goristange / Qebirstan", c: "religion" },
  { de: "Seele", ku: "Giyan / Rûh", c: "religion" },
  { de: "Paradies", ku: "Bihuşt / Cennet", c: "religion" },
  { de: "Hölle", ku: "Dojeh / Cehennem", c: "religion" },
  { de: "Engel", ku: "Firişte / Melek", c: "religion" },
  { de: "Segen", ku: "Xêr / Berekat", c: "religion" },
  { de: "Fasten", ku: "Rojî / Rêji", c: "religion" },
  { de: "Pilgerfahrt", ku: "Hec / Ziyaret", c: "religion" },
  { de: "heilig", ku: "pîroz / qudis", c: "religion" },
  { de: "Sünde", ku: "Guneh", c: "religion" },
  { de: "Vergebung", ku: "Lêborîn / Efû", c: "religion" },
  { de: "Barmherzigkeit", ku: "Rehm / Dilovanî", c: "religion" },

  // === PLACES — expand ===
  { de: "Apotheke", ku: "Dermanxane / Eczaxane", c: "places" },
  { de: "Bäckerei", ku: "Nanpêj / Firin", c: "places" },
  { de: "Metzgerei", ku: "Qesab / Goştfiroş", c: "places" },
  { de: "Bibliothek", ku: "Pirtûkxane / Kîtêbxane", c: "places" },
  { de: "Museum", ku: "Mûze / Muzexane", c: "places" },
  { de: "Kino", ku: "Sînema", c: "places" },
  { de: "Theater", ku: "Şano / Tiyatro", c: "places" },
  { de: "Brücke", ku: "Pir", c: "places" },
  { de: "Tunnel", ku: "Tûnel / Binerd", c: "places" },
  { de: "Hafen", ku: "Bender / Lîman", c: "places" },
  { de: "Dorf", ku: "Gund", c: "places" },
  { de: "Nachbarschaft", ku: "Taxe / Cîranî", c: "places" },
  { de: "Kreuzung", ku: "Çarçik / Xaçerê", c: "places" },
  { de: "Tankstelle", ku: "Benzînxane / Istasyona benzînê", c: "places" },
  { de: "Spielplatz", ku: "Qada lîstikê / Parkê zarokan", c: "places" },

  // === HEALTH — expand ===
  { de: "Impfung", ku: "Derzî / Vaknîs", c: "health" },
  { de: "Allergie", ku: "Alerjî / Hesasî", c: "health" },
  { de: "Verband", ku: "Sargî / Bandaj", c: "health" },
  { de: "Tablette", ku: "Heb / Tablet", c: "health" },
  { de: "Sirup", ku: "Şerbetê dermanê / Şîrop", c: "health" },
  { de: "Blutdruck", ku: "Tansiyona xwînê", c: "health" },
  { de: "Diabetes", ku: "Şekir / Diyabet", c: "health" },
  { de: "Operation", ku: "Emeliyat / Operasyon", c: "health" },
  { de: "Krankenwagen", ku: "Ambûlans", c: "health" },
  { de: "Notfall", ku: "Rewşa lezgîn / Acil", c: "health" },
  { de: "Schwangerschaft", ku: "Ducanî / Hamiletî", c: "health" },
  { de: "Geburt", ku: "Zayîn / Bûyîn", c: "health" },
  { de: "Zahnschmerzen", ku: "Êşa diran / Diranêş", c: "health" },
  { de: "Erkältung", ku: "Serabûn / Serhişk", c: "health" },
  { de: "Grippe", ku: "Grîp / Serma giran", c: "health" },

  // === TIME — expand ===
  { de: "Sekunde", ku: "Saniye / Çirkê", c: "time" },
  { de: "Minute", ku: "Deqe / Xûlek", c: "time" },
  { de: "Stunde", ku: "Saet / Demjimêr", c: "time" },
  { de: "Mitternacht", ku: "Nîvê şevê", c: "time" },
  { de: "Mittag", ku: "Nîvro", c: "time" },
  { de: "Morgendämmerung", ku: "Berbang / Spêde", c: "time" },
  { de: "Abenddämmerung", ku: "Êvar / Şefeq", c: "time" },
  { de: "Wochenende", ku: "Dawiya hefteyê", c: "time" },
  { de: "Feiertag", ku: "Roja betlaneyê / Cejn", c: "time" },
  { de: "Jahreszeit", ku: "Werz / Demsal", c: "time" },
  { de: "Frühling", ku: "Bihar / Buhar", c: "time" },
  { de: "Sommer", ku: "Havîn", c: "time" },
  { de: "Herbst", ku: "Payîz", c: "time" },
  { de: "Winter", ku: "Zivistan", c: "time" },
  { de: "Jahrhundert", ku: "Sedsalî / Qirn", c: "time" },

  // === EDUCATION — expand ===
  { de: "Zeugnis", ku: "Karnê / Şehadename", c: "education" },
  { de: "Abschluss", ku: "Mezûnî / Diploma", c: "education" },
  { de: "Stipendium", ku: "Bûrs / Mukafeya xwendinê", c: "education" },
  { de: "Prüfung", ku: "Azmûn / Îmtihan", c: "education" },
  { de: "Hausaufgabe", ku: "Erka malê / Wezîfe", c: "education" },
  { de: "Klassenzimmer", ku: "Polê xwendinê / Sinif", c: "education" },
  { de: "Tafel", ku: "Textê / Lewhê reş", c: "education" },
  { de: "Kreide", ku: "Tebaşîr", c: "education" },
  { de: "Bleistift", ku: "Qelem / Pênûs", c: "education" },
  { de: "Radiergummi", ku: "Lastîk / Silgî", c: "education" },
  { de: "Lineal", ku: "Xetkêş / Cetwel", c: "education" },
  { de: "Rucksack", ku: "Çente / Çanta", c: "education" },
  { de: "Wörterbuch", ku: "Ferheng", c: "education" },
  { de: "Grammatik", ku: "Rêziman / Gramer", c: "education" },
  { de: "Aussprache", ku: "Devok / Telaffuz", c: "education" },

  // === TRAVEL — expand ===
  { de: "Pass (Reisepass)", ku: "Pasaport / Derbasnameya rêwîtiyê", c: "travel" },
  { de: "Visum", ku: "Vîze", c: "travel" },
  { de: "Gepäck", ku: "Heqîbe / Bar", c: "travel" },
  { de: "Koffer", ku: "Valîz / Çente", c: "travel" },
  { de: "Fahrkarte", ku: "Bilêt / Tikêt", c: "travel" },
  { de: "Reservierung", ku: "Rezervasyon / Cihgirtin", c: "travel" },
  { de: "Ankunft", ku: "Gihîştin / Hatine", c: "travel" },
  { de: "Abfahrt", ku: "Derketin / Çûyîn", c: "travel" },
  { de: "Grenze", ku: "Sînor", c: "travel" },
  { de: "Zoll", ku: "Gumrik", c: "travel" },
  { de: "Botschaft", ku: "Balyozxane / Sefaret", c: "travel" },
  { de: "Stadtplan", ku: "Nexşeya bajêr", c: "travel" },
  { de: "Sehenswürdigkeit", ku: "Cihê dîtbarî / Cihê serdanê", c: "travel" },
  { de: "Souvenir", ku: "Bîranîn / Hediye", c: "travel" },
  { de: "Wechselstube", ku: "Sarrafxane / Cihê guherîna pereyan", c: "travel" },

  // === POLITICS — expand ===
  { de: "Wahl", ku: "Hilbijartin", c: "politics" },
  { de: "Demokratie", ku: "Dîmokrasî / Demokratî", c: "politics" },
  { de: "Freiheit", ku: "Azadî", c: "politics" },
  { de: "Gerechtigkeit", ku: "Dadperwerî / Edaletî", c: "politics" },
  { de: "Menschenrechte", ku: "Mafên mirovan", c: "politics" },
  { de: "Frieden", ku: "Aştî / Silh", c: "politics" },
  { de: "Krieg", ku: "Şer / Ceng", c: "politics" },
  { de: "Revolution", ku: "Şoreş / Înqîlab", c: "politics" },
  { de: "Protest", ku: "Xwepêşandan / Protesto", c: "politics" },
  { de: "Gesetz", ku: "Qanûn / Yasa", c: "politics" },
  { de: "Verfassung", ku: "Destûr / Makezagon", c: "politics" },
  { de: "Staatsbürgerschaft", ku: "Hemwelatîtî / Tabîyetî", c: "politics" },
  { de: "Botschafter", ku: "Balyoz / Sefîr", c: "politics" },
  { de: "Diplomat", ku: "Dîplomat", c: "politics" },
  { de: "Grenze", ku: "Sînor / Tixûb", c: "politics" },

  // === CLOTHING — expand ===
  { de: "Jacke", ku: "Çaket", c: "clothing" },
  { de: "Mantel", ku: "Palto / Berdêl", c: "clothing" },
  { de: "Pullover", ku: "Fanîle / Kazak", c: "clothing" },
  { de: "T-Shirt", ku: "Tîşêrt / Kiras", c: "clothing" },
  { de: "Rock", ku: "Etêk / Fîstan", c: "clothing" },
  { de: "Kleid", ku: "Fîstan / Kincê jinan", c: "clothing" },
  { de: "Socken", ku: "Gore / Çorap", c: "clothing" },
  { de: "Handschuh", ku: "Destik / Eldiwan", c: "clothing" },
  { de: "Mütze", ku: "Kumik / Şepik", c: "clothing" },
  { de: "Gürtel", ku: "Qayîş / Kember", c: "clothing" },
  { de: "Krawatte", ku: "Kravat / Stûbend", c: "clothing" },
  { de: "Brille", ku: "Berçavk / Çavîlk", c: "clothing" },
  { de: "Sonnenbrille", ku: "Berçavka rojê", c: "clothing" },
  { de: "Regenschirm", ku: "Sîwan / Çetr", c: "clothing" },
  { de: "Tasche", ku: "Çente / Torbe", c: "clothing" },

  // === HOUSE — expand ===
  { de: "Dach", ku: "Ban / Serban", c: "house" },
  { de: "Wand", ku: "Dîwar", c: "house" },
  { de: "Boden", ku: "Erd / Bin", c: "house" },
  { de: "Decke (Zimmerdecke)", ku: "Tavan / Stûyê odeyê", c: "house" },
  { de: "Treppe", ku: "Pêpeling / Derecan", c: "house" },
  { de: "Balkon", ku: "Balkon / Eywan", c: "house" },
  { de: "Garten", ku: "Baxçe / Bax", c: "house" },
  { de: "Zaun", ku: "Sûr / Çît", c: "house" },
  { de: "Steckdose", ku: "Prîz / Fîşê karebayê", c: "house" },
  { de: "Lampe", ku: "Çira / Lamba", c: "house" },
  { de: "Heizung", ku: "Germker / Şofaj", c: "house" },
  { de: "Klimaanlage", ku: "Klîma / Sarker", c: "house" },
  { de: "Waschmaschine", ku: "Makîna cilşûştinê", c: "house" },
  { de: "Kühlschrank", ku: "Serdest / Buzdolap", c: "house" },
  { de: "Herd", ku: "Ocax / Sobeya pêjgehê", c: "house" },

  // === PROFESSIONS — expand ===
  { de: "Pilot", ku: "Pîlot / Firînvan", c: "professions" },
  { de: "Koch", ku: "Aşpêj / Pêjger", c: "professions" },
  { de: "Friseur", ku: "Berber / Gêjker", c: "professions" },
  { de: "Elektriker", ku: "Karebaker / Elektrîkçî", c: "professions" },
  { de: "Mechaniker", ku: "Mîkanîker / Tamîrker", c: "professions" },
  { de: "Bauer", ku: "Cotkar / Rêncber", c: "professions" },
  { de: "Fischer", ku: "Masîgir", c: "professions" },
  { de: "Schriftsteller", ku: "Nivîskar", c: "professions" },
  { de: "Journalist", ku: "Rojnamevan", c: "professions" },
  { de: "Fotograf", ku: "Wênekêş / Fotograf", c: "professions" },
  { de: "Wissenschaftler", ku: "Zanist / Zanyar", c: "professions" },
  { de: "Dolmetscher", ku: "Wergêr / Tercûman", c: "professions" },
  { de: "Richter", ku: "Dadger / Hakim", c: "professions" },
  { de: "Feuerwehrmann", ku: "Agirkuj / Îtfaiyeci", c: "professions" },
  { de: "Krankenschwester", ku: "Hemşîre / Karmentê nexweşxaneyê", c: "professions" },

  // === GRAMMAR — useful words ===
  { de: "weil", ku: "ji ber ku / çimkî", c: "grammar" },
  { de: "obwohl", ku: "her çiqas / tevî ku", c: "grammar" },
  { de: "deshalb", ku: "ji ber vê yekê / lewre", c: "grammar" },
  { de: "trotzdem", ku: "dîsa jî / lê belê", c: "grammar" },
  { de: "falls", ku: "heke / eger", c: "grammar" },
  { de: "entweder...oder", ku: "yan...yan jî", c: "grammar" },
  { de: "weder...noch", ku: "ne...ne jî", c: "grammar" },
  { de: "sowohl...als auch", ku: "hem...hem jî", c: "grammar" },
  { de: "jeder", ku: "her kes / hemû", c: "grammar" },
  { de: "niemand", ku: "tu kes / kes ne", c: "grammar" },
  { de: "etwas", ku: "tiştekî / hindek", c: "grammar" },
  { de: "nichts", ku: "tu tişt / tiştekî ne", c: "grammar" },
  { de: "immer", ku: "her dem / hertim", c: "grammar" },
  { de: "nie", ku: "tu car / qet", c: "grammar" },
  { de: "manchmal", ku: "hên car / carinan", c: "grammar" },
];

async function seed() {
  console.log(`Inserting ${NEW_WORDS.length} new words...`);

  let inserted = 0;
  let skipped = 0;

  for (const word of NEW_WORDS) {
    try {
      await db.execute({
        sql: `INSERT INTO words (de, ku, category, is_phrase) VALUES (?, ?, ?, ?)
              ON CONFLICT(de, ku, category) DO NOTHING`,
        args: [word.de, word.ku, word.c, word.t || 0],
      });
      inserted++;
    } catch (e) {
      // Duplicate or other error
      skipped++;
    }
  }

  // Count totals
  const result = await db.execute('SELECT COUNT(*) as cnt FROM words');
  const total = result.rows[0].cnt;

  console.log(`Done! Inserted: ${inserted}, Skipped: ${skipped}`);
  console.log(`Total words in DB: ${total}`);

  process.exit(0);
}

seed().catch((e) => {
  console.error('Seed error:', e);
  process.exit(1);
});
